MovieStore_Chili/Models/Database/Order.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MovieStore_Chili.Models.Database
{
    public class Order
    {
        public int Id { get; set; }

        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime OrderDate { get; set; }

        [Required]
        public int CustomerId { get; set; }

        [ForeignKey("CustomerId")]
        public virtual Customer? Customer { get; set; }

        public virtual ICollection<OrderRow> OrderRows { get; set; } =
            new List<OrderRow>();
    }
}

MovieStore_Chili/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using MovieStore_Chili.Models.Database;
using MovieStore_Chili.Services;

namespace MyMovieShopProject.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }
        public IActionResult CustomerSearch()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateOrShow(string Email)
        {
            Customer customer = _customerService.GetCustomerByEmail(Email);
            if (customer == null)
            {
                return RedirectToAction("Create");
            }
            else
            {
                HttpContext.Session.SetInt32("SelectedCustomer", customer.Id);
                return RedirectToAction("Detail", new { id = customer.Id });
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                _customerService.AddCustomer(customer);
                customer = _customerService.GetCustomerByEmail(customer.Email);
                HttpContext.Session.SetInt32("SelectedCustomer", customer.Id);
                return RedirectToAction("OrderCreate", "Order");
            }
            return View();
        }

        public IActionResult Detail(int id)
        {
            Customer customer = _customerService.GetCustomerById(id);
            return View(customer);
        }

        public IActionResult Edit(int id)
        {
            var customer = _customerService.GetCustomerById(id);
            return View(customer);
        }

        [HttpPost]
        public IActionResult Edit(Customer customer)
        {
            _customerService.UpdateCustomer(customer);
            return RedirectToAction(nameof(Detail), new { id = customer.Id });
        }
    }
}

MovieStore_Chili/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieStore_Chili.Data;
using MovieStore_Chili.Models.Database;
using MovieStore_Chili.Services;
using PagedList;

namespace MovieStore_Chili.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;

        public MovieController(IMovieService movieService)
        {
            _movieService = movieService;
        }
        public IActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            var movies = _movieService.GetMovies();
            var moviePage = movies.ToPagedList(pageNumber, 4);
            return View(moviePage);
        }   
        public IActionResult Admin()
        {
            var movies = _movieService.GetMovies();
            return View(movies);
        }

        public IActionResult AddToCart(int id)
        {
            string SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            if (SelectedMovieIds == null)
            {
                SelectedMovieIds = id.ToString();
            }
            else
            {
                SelectedMovieIds = SelectedMovieIds + "," + id.ToString();
            }
            HttpContext.Session.SetString("SelectedMovieIds", SelectedMovieIds);
            return Redirect("Index");
        }
        public IActionResult AddToCartFromDashBoard(int id)
        {
            string SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            if (SelectedMovieIds == null)
            {
                SelectedMovieIds = id.ToString();
            }
            else
            {
                SelectedMovieIds = SelectedMovieIds + "," + id.ToString();
            }
            HttpContext.Session.SetString("SelectedMovieIds", SelectedMovieIds);
            return Json(new { success = true });
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Movie movie)
        {
            if (ModelState.IsValid)
            {
                _movieService.AddMovie(movie);
                return RedirectToAction(nameof(Admin));
            }
            return View();
        }
        public IActionResult Delete(int id)
        {
            var movie = _movieService.GetMovieById(id);
            return View(movie);
        }
        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            _movieService.RemoveMovie(id);
            return RedirectToAction(nameof(Admin));
        }
        public IActionResult Edit(int id)
        {
            var movie = _movieService.GetMovieById(id);
            return View(movie);
        }

        [HttpPost]
        public IActionResult Edit(Movie movie)
        {
            _movieService.UpdateMovie(movie);
            return RedirectToAction(nameof(Admin));
        }

        public IActionResult AboutUs()
        {
            return View();
        }
        
    }
}

MovieStore_Chili/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieStore_Chili.Models.Database;
using MovieStore_Chili.Services;
using MovieStore_Chili.Helpers;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using Microsoft.EntityFrameworkCore;
using MovieStore_Chili.Data;
using System.Net.Mail;


namespace MovieStore_Chili.Controllers
{
    public class OrderController : Controller
    {

        const string sessionPassword = "Password";

        private readonly IMovieService _movieService;
        private readonly IOrderService _orderService;
        private readonly ICustomerService _customerService;
        private readonly MovieDbContext _db;

        public OrderController(IMovieService movieService, IOrderService orderService, ICustomerService customerService, MovieDbContext db)
        {
            _movieService = movieService;
            _orderService = orderService;
            _customerService = customerService;
            _db = db;
        }


        public IActionResult Index()
        {


            return View();
        }

        public IActionResult AllOrder()
        {
            if (HttpContext.Session.Get<string>(sessionPassword) == default)
            {
                return RedirectToAction("Entrance");
            }

            var orders = _orderService.GetOrderInDetail();
            return View(orders);
        }

        [HttpGet]
        public IActionResult Entrance()
        {
            return View();
        }

        public IActionResult OrderCreate()
        {
            Order order = new Order();
            order.CustomerId = Convert.ToInt32(HttpContext.Session.GetInt32("SelectedCustomer"));
            order.OrderDate = DateTime.Now;
            order.OrderRows = GetOrderRowsFromSession();


            _orderService.AddOrder(order);
            HttpContext.Session.Clear();

            return RedirectToAction("Detail", new { id = order.Id });

        }

        public IActionResult Detail(int id)
        {
            Order order = _orderService.GetOrderById(id);
            return View(order);
        }

        [HttpPost]
        public IActionResult Entrance(string inputPassword)
        {
            if (inputPassword == "chiLi")
            {
                HttpContext.Session.Set<string>(sessionPassword, inputPassword);
                return RedirectToAction("AllOrder");
            }

            return View();
        }



        public IActionResult SelectedMovieList()
        {
            List<OrderRow> orderRows = GetOrderRowsFromSession();
            return View(orderRows);
        }

        private List<OrderRow> GetOrderRowsFromSession()
        {
            List<OrderRow> orderRows = new List<OrderRow>();

            string? SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            if (SelectedMovieIds != null)
            {
                int[] movieIds = SelectedMovieIds.Split(',').Select(n => int.Parse(n)).ToArray();
                Array.Sort(movieIds);
                foreach (var movieId in movieIds)
                {
                    bool alredyAdded = false;
                    foreach (var orderRow in orderRows)
                    {
                        if (orderRow.MovieId == movieId)
                        {
                            alredyAdded = true;
                            orderRow.Quantity = orderRow.Quantity + 1;
                            orderRow.Price = orderRow.Movie.Price * orderRow.Quantity;
                            break;
                        }
                    }
                    if (!alredyAdded)
                    {
                        var movie = _movieService.GetMovieById(movieId);
                        OrderRow orderRow = new OrderRow();
                        orderRow.MovieId = movieId;
                        orderRow.Movie = movie;
                        orderRow.Quantity = 1;
                        orderRow.Price = movie.Price;
                        orderRows.Add(orderRow);
                    }
                }
            }
            return orderRows;
        }

        public IActionResult AddToCart(int id)
        {
            string SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            if (SelectedMovieIds == null)
            {
                SelectedMovieIds = id.ToString();
            }
            else
            {
                SelectedMovieIds = SelectedMovieIds + "," + id.ToString();
            }
            HttpContext.Session.SetString("SelectedMovieIds", SelectedMovieIds);
            return RedirectToAction("SelectedMovieList");
        }

        public IActionResult RemoveOneFromCart(int id)
        {
            string SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            string[] ids = SelectedMovieIds.Split(',');
            int indexToRemove = Array.IndexOf(ids, id.ToString());

            string newSelectedMovieIds = "";

            for (int i = 0; i < ids.Length; i++)
            {
                if (i != indexToRemove)
                {
                    if (newSelectedMovieIds.Length == 0)
                    {
                        newSelectedMovieIds = ids[i];
                    }
                    else
                    {
                        newSelectedMovieIds = newSelectedMovieIds + ',' + ids[i];
                    }
                }
            }

            if (newSelectedMovieIds.Length > 0)
            {
                HttpContext.Session.SetString("SelectedMovieIds", newSelectedMovieIds);
            }
            else
            {
                HttpContext.Session.Remove("SelectedMovieIds");
            }
            return RedirectToAction("SelectedMovieList");
        }

        public IActionResult RemoveFromCart(int id)
        {
            string SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            string[] ids = SelectedMovieIds.Split(',');

            string newSelectedMovieIds = "";

            for (int i = 0; i < ids.Length; i++)
            {
                if (ids[i] != id.ToString())
                {
                    if (newSelectedMovieIds.Length == 0)
                    {
                        newSelectedMovieIds = ids[i];
                    }
                    else
                    {
                        newSelectedMovieIds = newSelectedMovieIds + ',' + ids[i];
                    }
                }
            }

            if (newSelectedMovieIds.Length > 0)
            {
                HttpContext.Session.SetString("SelectedMovieIds", newSelectedMovieIds);
            }
            else
            {
                HttpContext.Session.Remove("SelectedMovieIds");
            }
            return Redirect("SelectedMovieList");
        }
        public IActionResult CustomersOrders()
        {
            return View();

        }
        [HttpPost]
        public IActionResult ShowCustomerOrders(string Email)
        {
            var customer = _customerService.GetCustomerByEmail(Email);

            if (customer == null)
            {
                return NotFound();
            }

            var customerOrders = _db.Orders
                .Where(o => o.CustomerId == customer.Id)
                .Include(o => o.OrderRows)
                    .ThenInclude(or => or.Movie)
                .ToList();

            return View(customerOrders);
        }

    }

}

MovieStore_Chili/Views/Order/AllOrder.cshtml
@model IEnumerable<MovieStore_Chili.Models.Database.Order>

<table class="table table-striped">
    <thead>
        <tr>
            
            <th>Customer Name</th>
            <th>Movie Title</th>
            <th>Date</th>
            <th>Total Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
            <tr>
                
                <td>@order.Customer.FirstName @order.Customer.LastName</td>

                <td >
                    @foreach (var orderRow in order.OrderRows)
                    {
                        @orderRow.Movie.Title

                        <br />
                    }
                </td>

                <td>@order.OrderDate</td>
                <td>@CalculateTotalPrice(order) Kr</td>
            </tr>
        }
    </tbody>
</table>

@functions {
    decimal CalculateTotalPrice(MovieStore_Chili.Models.Database.Order order)
    {
        if (order is null)
        {
            throw new ArgumentNullException(nameof(order));
        }

        decimal totalPrice = 0;
        foreach (var orderRow in order.OrderRows)
        {
            totalPrice += orderRow.Price;
        }
        return totalPrice;
    }
}

MovieStore_Chili/Views/Order/CustomersOrders.cshtml
@model MovieStore_Chili.Models.Database.Customer

@{
    ViewData["Title"] = "CustomersOrders";
}

<h1>Customers Orders</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Order" asp-action="ShowCustomerOrders">
            <div class="form-group">
                <label class="control-label">Email</label>
                <input type="text" class="form-control" asp-for="Email" />
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Next" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-controller="Movie" asp-action="Index">Back to List</a>
</div>

MovieStore_Chili/Views/Order/Detail.cshtml
@model MovieStore_Chili.Models.Database.Order

@{
    ViewData["Title"] = "Detail";
}

<div class="mt-4">
    <h3 class="text-center text-success"> The Order was successfully completed</h3>
</div>
<div class="mt-3">
    <hr />
    <div class="row">
        <div class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.OrderDate)
        </div>

        <div class="row">
        <div class="col-sm-2">
            Name
        </div>
        <div class="col-sm-6">
            @Html.DisplayFor(model => model.Customer.FirstName)
            @Html.DisplayFor(model => model.Customer.LastName)
        </div>
        </div>

        <div class="row">
        <div class="col-sm-2">
            @Html.DisplayNameFor(model => model.Customer.DeliveryAddress)
        </div>
        <div class="col-sm-6">
            @Html.DisplayFor(model => model.Customer.DeliveryAddress)
        </div>
        </div>

        <div class="row">
        <div class="col-sm-2">
            @Html.DisplayNameFor(model => model.Customer.BillingAddress)
        </div>
        <div class="col-sm-6">
            @Html.DisplayFor(model => model.Customer.BillingAddress)
        </div>
        </div>

        <div class="row">
        <div class="col-sm-2">
            @Html.DisplayNameFor(model => model.Customer.PhoneNumber)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.Customer.PhoneNumber)
        </div>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
            </th>
            <th>
                Title
            </th>
            <th>
                Director
            </th>
            <th>
                Price
            </th>
        </tr>
    </thead>
    <tbody>

        @{
            decimal total = 0;
        }

        @foreach (var item in Model.OrderRows)
        {
            total = total + item.Price;
            <tr class="mt-3">
                <td>
                    <img style="height:60px;width:80px" src="/Images/@item.Movie.Image">
                    @* @Html.DisplayFor(modelItem => item.Movie.Image) *@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Movie.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Movie.Director)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
            </tr>
        }
        <tr>
            <th colspan="3">
                Total Amount
            </th>
            <th>
                @total
            </th>
        </tr>
    </tbody>
</table>
<h4 class="text-center text-success">Thank you for your order! Your order will be received with in 3 days</h4>

MovieStore_Chili/Views/Order/Entrance.cshtml
<div class="container p-5 my-5 border col-8 text-center">
    <form asp-action="Entrance">
        <div class="form-group">
            <input name="inputPassword" type="text" placeholder="Password" />

        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Continue" class="btn btn-outline-success" />

        </div>

    </form>
</div>

MovieStore_Chili/Views/Order/SelectedMovieList.cshtml
@model IEnumerable<MovieStore_Chili.Models.Database.OrderRow>

@{
    ViewData["Title"] = "Create";
}
<html>
    <body>


<h1>Shopping Cart</h1>
<br/>
<hr/>
<table class="table" id="shoppingCartTable">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movie.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movie.Director)
            </th>
            <th>
                Quantity
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>

            </th>

        </tr>
    </thead>
    <tbody>

        @{
            decimal total = 0;
        }

        @foreach (var item in Model)
        {
            total = total + item.Price;
            <tr>
                <td>
                    <img style="height:60px;width:80px" src="/Images/@item.Movie.Image">
                    @* @Html.DisplayFor(modelItem => item.Movie.Image) *@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Movie.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Movie.Director)
                </td>
                    <td>
                        <div class="btn-group" role="group">
                            @if (item.Quantity == 1)
                            {
                                <a asp-action="RemoveOneFromCart" asp-route-id="@item.Movie.Id" class="disabled btn btn-outline-primary">-</a>
                            }
                            else
                            {
                                <a asp-action="RemoveOneFromCart" asp-route-id="@item.Movie.Id" class="btn btn-outline-primary">-</a>
                            }
                            <input type="button" value="@item.Quantity" class="p-2">
                            <a asp-action="AddToCart" asp-route-id="@item.Movie.Id" class="btn btn-outline-primary">+</a>
                        </div>
                    </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <a class="btn btn-danger" asp-action="RemoveFromCart" asp-route-id="@item.Movie.Id">Delete</a>
                </td>
            </tr>
        }

        <tr>
            <th colspan="4">
                Total Amount
            </th>
            <th>
                @total
            </th>
            <th>

            </th>
        </tr>
    </tbody>
</table>

<a class="btn btn-success" asp-controller="Movie" asp-action="Index">Back</a>

<a class="btn btn-success" asp-controller="Customer" asp-action="CustomerSearch">Check Out</a>

</body>
</html>

MovieStore_Chili/Views/Order/ShowCustomerOrders.cshtml
@model List<MovieStore_Chili.Models.Database.Order>


<h2 align="center">Order List</h2>
 @Html.Partial("_ShowCustomerOrdersPartial", Model) 

MovieStore_Chili/Views/Order/_ShowCustomerOrdersPartial.cshtml
@model List<MovieStore_Chili.Models.Database.Order>

<div class="container">
    
    @foreach (var row in Model)
    {
        <div class="col-md-66">
            <h3> Customer Name: @row.Customer.FirstName @row.Customer.LastName </h3>
        </div>
        break;
    }
    <h3>Total Orders :@Model.Count</h3>
    <table class="table table-striped">
        <thead>
            <tr>
              <th>Order Date</th>
              <th>Movie Title</th>
              <th>Delivery Address</th>
               <th>Total Price</th>
            
           </tr>
        </thead>
       
    @foreach (var row in Model)
    {
       <tr>
         <td> @row.OrderDate</td>
         
         <td>
                    @foreach (var orderRow in row.OrderRows)
                    {
                        @orderRow.Movie.Title

                        <br />
                    }
                </td>
       <td>@row.Customer.DeliveryAddress </td>

        <td>@row.OrderRows.Sum(or => or.Movie.Price) Kr</td>

       </tr>
        }
    </table>
    
</div>