MovieStore_Chili/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieStore_Chili.Data;
using MovieStore_Chili.Models.Database;
using MovieStore_Chili.Services;
using PagedList;

namespace MovieStore_Chili.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;

        public MovieController(IMovieService movieService)
        {
            _movieService = movieService;
        }
        public IActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            var movies = _movieService.GetMovies();
            var moviePage = movies.ToPagedList(pageNumber, 4);
            return View(moviePage);
        }   
        public IActionResult Admin()
        {
            var movies = _movieService.GetMovies();
            return View(movies);
        }

        public IActionResult AddToCart(int id)
        {
            string SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            if (SelectedMovieIds == null)
            {
                SelectedMovieIds = id.ToString();
            }
            else
            {
                SelectedMovieIds = SelectedMovieIds + "," + id.ToString();
            }
            HttpContext.Session.SetString("SelectedMovieIds", SelectedMovieIds);
            return Redirect("Index");
        }
        public IActionResult AddToCartFromDashBoard(int id)
        {
            string SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            if (SelectedMovieIds == null)
            {
                SelectedMovieIds = id.ToString();
            }
            else
            {
                SelectedMovieIds = SelectedMovieIds + "," + id.ToString();
            }
            HttpContext.Session.SetString("SelectedMovieIds", SelectedMovieIds);
            return Json(new { success = true });
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Movie movie)
        {
            if (ModelState.IsValid)
            {
                _movieService.AddMovie(movie);
                return RedirectToAction(nameof(Admin));
            }
            return View();
        }
        public IActionResult Delete(int id)
        {
            var movie = _movieService.GetMovieById(id);
            return View(movie);
        }
        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            _movieService.RemoveMovie(id);
            return RedirectToAction(nameof(Admin));
        }
        public IActionResult Edit(int id)
        {
            var movie = _movieService.GetMovieById(id);
            return View(movie);
        }

        [HttpPost]
        public IActionResult Edit(Movie movie)
        {
            _movieService.UpdateMovie(movie);
            return RedirectToAction(nameof(Admin));
        }

        public IActionResult AboutUs()
        {
            return View();
        }
        
    }
}

MovieStore_Chili/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieStore_Chili.Models.Database;
using MovieStore_Chili.Services;
using MovieStore_Chili.Helpers;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using Microsoft.EntityFrameworkCore;
using MovieStore_Chili.Data;
using System.Net.Mail;


namespace MovieStore_Chili.Controllers
{
    public class OrderController : Controller
    {

        const string sessionPassword = "Password";

        private readonly IMovieService _movieService;
        private readonly IOrderService _orderService;
        private readonly ICustomerService _customerService;
        private readonly MovieDbContext _db;

        public OrderController(IMovieService movieService, IOrderService orderService, ICustomerService customerService, MovieDbContext db)
        {
            _movieService = movieService;
            _orderService = orderService;
            _customerService = customerService;
            _db = db;
        }


        public IActionResult Index()
        {


            return View();
        }

        public IActionResult AllOrder()
        {
            if (HttpContext.Session.Get<string>(sessionPassword) == default)
            {
                return RedirectToAction("Entrance");
            }

            var orders = _orderService.GetOrderInDetail();
            return View(orders);
        }

        [HttpGet]
        public IActionResult Entrance()
        {
            return View();
        }

        public IActionResult OrderCreate()
        {
            Order order = new Order();
            order.CustomerId = Convert.ToInt32(HttpContext.Session.GetInt32("SelectedCustomer"));
            order.OrderDate = DateTime.Now;
            order.OrderRows = GetOrderRowsFromSession();


            _orderService.AddOrder(order);
            HttpContext.Session.Clear();

            return RedirectToAction("Detail", new { id = order.Id });

        }

        public IActionResult Detail(int id)
        {
            Order order = _orderService.GetOrderById(id);
            return View(order);
        }

        [HttpPost]
        public IActionResult Entrance(string inputPassword)
        {
            if (inputPassword == "chiLi")
            {
                HttpContext.Session.Set<string>(sessionPassword, inputPassword);
                return RedirectToAction("AllOrder");
            }

            return View();
        }



        public IActionResult SelectedMovieList()
        {
            List<OrderRow> orderRows = GetOrderRowsFromSession();
            return View(orderRows);
        }

        private List<OrderRow> GetOrderRowsFromSession()
        {
            List<OrderRow> orderRows = new List<OrderRow>();

            string? SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            if (SelectedMovieIds != null)
            {
                int[] movieIds = SelectedMovieIds.Split(',').Select(n => int.Parse(n)).ToArray();
                Array.Sort(movieIds);
                foreach (var movieId in movieIds)
                {
                    bool alredyAdded = false;
                    foreach (var orderRow in orderRows)
                    {
                        if (orderRow.MovieId == movieId)
                        {
                            alredyAdded = true;
                            orderRow.Quantity = orderRow.Quantity + 1;
                            orderRow.Price = orderRow.Movie.Price * orderRow.Quantity;
                            break;
                        }
                    }
                    if (!alredyAdded)
                    {
                        var movie = _movieService.GetMovieById(movieId);
                        OrderRow orderRow = new OrderRow();
                        orderRow.MovieId = movieId;
                        orderRow.Movie = movie;
                        orderRow.Quantity = 1;
                        orderRow.Price = movie.Price;
                        orderRows.Add(orderRow);
                    }
                }
            }
            return orderRows;
        }

        public IActionResult AddToCart(int id)
        {
            string SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            if (SelectedMovieIds == null)
            {
                SelectedMovieIds = id.ToString();
            }
            else
            {
                SelectedMovieIds = SelectedMovieIds + "," + id.ToString();
            }
            HttpContext.Session.SetString("SelectedMovieIds", SelectedMovieIds);
            return RedirectToAction("SelectedMovieList");
        }

        public IActionResult RemoveOneFromCart(int id)
        {
            string SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            string[] ids = SelectedMovieIds.Split(',');
            int indexToRemove = Array.IndexOf(ids, id.ToString());

            string newSelectedMovieIds = "";

            for (int i = 0; i < ids.Length; i++)
            {
                if (i != indexToRemove)
                {
                    if (newSelectedMovieIds.Length == 0)
                    {
                        newSelectedMovieIds = ids[i];
                    }
                    else
                    {
                        newSelectedMovieIds = newSelectedMovieIds + ',' + ids[i];
                    }
                }
            }

            if (newSelectedMovieIds.Length > 0)
            {
                HttpContext.Session.SetString("SelectedMovieIds", newSelectedMovieIds);
            }
            else
            {
                HttpContext.Session.Remove("SelectedMovieIds");
            }
            return RedirectToAction("SelectedMovieList");
        }

        public IActionResult RemoveFromCart(int id)
        {
            string SelectedMovieIds = HttpContext.Session.GetString("SelectedMovieIds");
            string[] ids = SelectedMovieIds.Split(',');

            string newSelectedMovieIds = "";

            for (int i = 0; i < ids.Length; i++)
            {
                if (ids[i] != id.ToString())
                {
                    if (newSelectedMovieIds.Length == 0)
                    {
                        newSelectedMovieIds = ids[i];
                    }
                    else
                    {
                        newSelectedMovieIds = newSelectedMovieIds + ',' + ids[i];
                    }
                }
            }

            if (newSelectedMovieIds.Length > 0)
            {
                HttpContext.Session.SetString("SelectedMovieIds", newSelectedMovieIds);
            }
            else
            {
                HttpContext.Session.Remove("SelectedMovieIds");
            }
            return Redirect("SelectedMovieList");
        }
        public IActionResult CustomersOrders()
        {
            return View();

        }
        [HttpPost]
        public IActionResult ShowCustomerOrders(string Email)
        {
            var customer = _customerService.GetCustomerByEmail(Email);

            if (customer == null)
            {
                return NotFound();
            }

            var customerOrders = _db.Orders
                .Where(o => o.CustomerId == customer.Id)
                .Include(o => o.OrderRows)
                    .ThenInclude(or => or.Movie)
                .ToList();

            return View(customerOrders);
        }

    }

}

MovieStore_Chili/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieStore_Chili</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/MyTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link href="~/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/MovieStore_Chili.styles.css" asp-append-version="true" />
</head>
<body>
    
    <header>
        <div>
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/Logo12.png" height=50px; width=150px; /></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                            <li class="nav-item">
                                <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Movie" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle fw-bold" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Search by
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="Home" asp-action="SortedByPopularMovies">Populer Movies</a></li>
                                    <li><a class="dropdown-item" asp-controller="Home" asp-action="SortedByOldest">Oldest Movies</a></li>
                                    <li><a class="dropdown-item" asp-controller="Home" asp-action="SortedByCheapest">Cheapest Movies</a></li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Home" asp-action="SortedByNewest">Newest Movies
                                     </a>
                                        </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Home" asp-action="MostExpensiveOrder">
                                            MostExpensiveCustomer
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle fw-bold" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    OrderList
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="Order" asp-action="CustomersOrders">Customer Orders</a></li>
                                    <li><a class="dropdown-item" asp-controller="Order" asp-action="AllOrder">All Orders</a></li>
                                  
                                   
                                </ul>
                            </li>
                            </li>
                            <li class="nav-item fw-bold">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="AboutUs"> About Us </a>
                            </li>
                            <li class="nav-item fw-bold">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="SelectedMovieList">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l.84 4.479 9.144-.459L13.89 4zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2" />
                                    </svg>
                                    @if (Context.Session.GetString("SelectedMovieIds") != null)
                                    {
                                        var itemCount = Context.Session.GetString("SelectedMovieIds").Split(',').Length;
                                        <div class="item-count cart-icon">
                                        @itemCount
                                        </div>
                                    }

                                </a>
                            </li>
                            @* <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index"> Order </a>
                            </li> *@
                            
                        </ul>
                        @* <form class="d-flex" role="search">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form> *@
                        <div>
                            <form class="d-flex" method="get" action="@Url.Action("SearchByTitle", "Home")">

                                <input class="form-control me-2"type="text" placeholder="Search by title" name="search" id="search" />
                                <button class="btn btn-success type="submit">Search</button>
                        </form>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container container">
            &copy; 2024 - MovieStore_Chili - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>